#!/usr/bin/env python

import boatdclient

from navigate import Navigator

points = None


class TestBehaviour(Navigator):
    def __init__(self):
        super(TestBehaviour, self).__init__()
        self.set_target(points[0])
        self.current_point = 0

    def check_new_target(self):
        distance = self.boat.position.distance_to(self.target)
        if distance <= 10:
            print('distance from point:', distance)
            self.current_point += 1
            return points[self.current_point]
        else:
            print('distance to point', distance)
            return None

if __name__ == '__main__':
    behaviour = TestBehaviour()
    behaviour.run()
