#!/usr/bin/env python
import time

import boatdclient
from boatdclient import Point, Bearing

from navigate import Navigator


class IdleBehaviour(Navigator):
    def __init__(self):
        super(IdleBehaviour, self).__init__()
        self.home_point = boatdclient.get_home_position()
        self.init_point = self.boat.position()
        if self.home_point == None
            self.set_target(self.init_point)
        else 
            self.set_target(self.home_point)
                
        
    def check_new_target(self):   
        pass     


if __name__ == '__main__':
    behaviour = IdleBehaviour()
    behaviour.run()
