#!/usr/bin/env python3

import time

import boatdclient


class IdleBehaviour(object):
    def __init__(self):
        self.boat = boatdclient.Boat(convenience=True)

    def run(self):
        while True:
            wind_direction = self.boat.wind.direction

            heading_error = (wind_direction - self.boat.heading) - 180

            if float(heading_error) < 180:
                self.boat.set_rudder(float(heading_error)-360)
            else:
                self.boat.set_rudder(heading_error)

            print('error:', heading_error)

            print(self.boat.heading, wind_direction)
            time.sleep(0.5)


if __name__ == '__main__':
    behaviour = IdleBehaviour()
    behaviour.run()
