#!/usr/bin/env python

import boatdclient

from navigate import Navigator

points = boatdclient.get_current_waypoints()


class VirtualAnchoringBehaviour(Navigator):
    def __init__(self):
        super(VirtualAnchoringBehaviour, self).__init__(enable_tacking=True,
                                                        enable_cross_track_minimization=False)
        self.set_target(points[0])

    def check_new_target(self):
        distance = self.boat.position.distance_to(self.target)

        print ('distance from point:', distance)
        return points[0]


if __name__ == '__main__':
    behaviour = VirtualAnchoringBehaviour()
    behaviour.run()
