#!/usr/bin/env python
import time

import boatdclient
from boatdclient import Point, Bearing

from navigate import Navigator

points = boatdclient.get_current_waypoints()
minutes_in_box = 5

class StationKeepingBehaviour(Navigator):
    def __init__(self):
        super(StationKeepingBehaviour, self).__init__(enable_tacking=False)
        self.center = (points[0] + points[1] + points[2] + points[3]) / 4
        self.set_target(self.center)
        self.edge_bearing_to_center = None
        self.center_reached = False
        self.line_crossed = False
        self.enter_time = None
        self.time_to_center = None
        
        sorted_points = []
        for point in points:
            sorted_points.append((self.boat.position.distance_to(point), point))
        self.nearest_line_points = sorted(sorted_points, key=lambda x: x[0])
        self.nearest_line_points = [n[1] for n in self.nearest_line_points][0:2]
        
        if self.boat.position.cross_track_distance(self.nearest_line_points[1], self.nearest_line_points[0]) < 0:
            self.start_negative = True
        else:
            self.start_negative = False

    def check_new_target(self):
        if self.boat.position.distance_to(self.center) < 1:
            if self.center_reached is False:
                self.time_to_center = time.time() - self.enter_time
            self.center_reached = True

        if self.center_reached is False:             
            if  (self.boat.position.cross_track_distance(self.nearest_line_points[1], self.nearest_line_points[0]) <= 0 and \
                self.start_negative is False) or (self.boat.position.cross_track_distance(self.nearest_line_points[1], \
                self.nearest_line_points[0]) >= 0 and self.start_negative is True):
                      
                print 'YOU HAVE CROSSED THE LINE ' * 20
                self.line_crossed = True
                self.enter_time = time.time()
                self.bearing_edge_to_center = self.boat.position.bearing_to(self.center)

            return None

        elif self.center_reached is True:
            if time.time() < self.enter_time + (minutes_in_box * 60) - self.time_to_center:
                return None
            else:
                return self.bearing_edge_to_center


if __name__ == '__main__':
    behaviour = StationKeepingBehaviour()
    behaviour.run()
