#!/usr/bin/env python3

from boatdclient import Point

from navigate import Navigator

points = [Point(0.001, 0.0005), Point(0.0001, 0)]

class StationKeepingBehaviour(Navigator):
    def __init__(self):
        super().__init__(enable_tacking=False)

    def check_new_target(self):
        return None

if __name__ == '__main__':
    behaviour = StationKeepingBehaviour()
    behaviour.run()
